### PR TITLE
Add changes to all-MiniLM-L6-v2 documentation

### PR DESCRIPTION
**Pull request by NonMundaneDev**

### CODE REVIEW

**Comment by filippopedrazzinifp** [comment]
@NonMundaneDev looks good, but you need to put links in this format:

<a href='https://huggingface.co/databricks/dolly-v2-12b' target='_blank'>Learn More</a>

Otherwise from the desktop app, people will not be able to click on them

**Comment by filippopedrazzinifp** [comment]
@tiero do you have any other comments? Do you want more explanation about embeddings are?

**Comment by NonMundaneDev** [comment]
> @NonMundaneDev looks good, but you need to put links in this format:
> 
> ```gfm
> <a href='https://huggingface.co/databricks/dolly-v2-12b' target='_blank'>Learn More</a>
> ```
> 
> Otherwise from the desktop app, people will not be able to click on them

Okay. I see. I will add this to the style guide now.

**Comment by NonMundaneDev** [comment]
@filippopedrazzinifp, updated the anchor links with the latest commit. Thank you.

**Pull request merged**
